######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 26 00:05:14 2014
######################################################################

TEMPLATE = subdirs

# Directories

include(/usr/src/cpp/common.pri)

