######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 15 13:03:57 2015
######################################################################

TEMPLATE = subdirs

# Directories

include(/usr/src/cpp/common.pri)

